#!/bin/bash
# Update and install dependencies
yum update -y
sudo amazon-linux-extras install java-openjdk11 -y

# Download and install SonarQube
wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.8.0.63668.zip
unzip sonarqube-9.8.0.63668.zip -d /opt
mv /opt/sonarqube-9.8.0.63668 /opt/sonarqube

# Create a dedicated user for SonarQube
useradd -r -s /bin/false sonarqube
chown -R sonarqube:sonarqube /opt/sonarqube

# Start SonarQube
sudo -u sonarqube /opt/sonarqube/bin/linux-x86-64/sonar.sh start
